### ISSUE TITLE
If kernel does not exist with firecracker it crashes

### ISSUE THREAD

**Issue by jensg-st** [vorteil/vorteil#40]
```
Writing image done [==============================================================================] 46.0 MiB / 46.0 MiB
Error: Kernel '20.9.5' VMLinux does not exist
^Cpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x188 pc=0x21aa4b6]

goroutine 27 [running]:
github.com/firecracker-microvm/firecracker-go-sdk.(*Machine).Shutdown(0x0, 0x0, 0x0, 0x0, 0x0)
	/home/jensg/go/pkg/mod/github.com/firecracker-microvm/firecracker-go-sdk@v0.21.0/machine.go:410 +0x26
github.com/vorteil/vorteil/pkg/virtualizers/firecracker.(*Virtualizer).Stop(0xc00014e840, 0x0, 0x0)
	/tmp/vorteil/pkg/virtualizers/firecracker/virtualizer_linux.go:542 +0xbc
main.run.func2(0x2d3cd80, 0xc00014e840, 0xc0001ab690)
	/tmp/vorteil/cmd/vorteil/run.go:385 +0x35
created by main.run
	/tmp/vorteil/cmd/vorteil/run.go:384 +0x7bb
```

**Comment by trentis** [comment]
Resolved in https://github.com/vorteil/vorteil/pull/44
