### ISSUE TITLE
if running qemu is not permitted it crashes

### ISSUE THREAD

**Issue by jensg-st** [vorteil/vorteil#41]
```qemu-system-x86_64: failed to initialize KVM: Permission denied

Error: unable to start QEMU as socket wasn't created in time

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x225154a]

goroutine 114 [running]:

github.com/vorteil/vorteil/pkg/virtualizers/qemu.(*Virtualizer).Start.func1(0xc000724000, 0xc001fc65e0)

	/home/travis/gopath/src/github.com/vorteil/vorteil/pkg/virtualizers/qemu/virtualizer_notwindows.go:75 +0x58a

created by github.com/vorteil/vorteil/pkg/virtualizers/qemu.(*Virtualizer).Start

	/home/travis/gopath/src/github.com/vorteil/vorteil/pkg/virtualizers/qemu/virtualizer_notwindows.go:38 +0x1d9

Makefile:84: recipe for target 'test' failed```

**Comment by trentis** [comment]
Resolved in https://github.com/vorteil/vorteil/pull/44
